include: package:lints/recommended.yaml

linter:
  rules:
    camel_case_types: true
    avoid_print: true
    constant_identifier_names: false
    prefer_final_locals: true
    prefer_final_in_for_each: true
    avoid_dynamic_calls: true

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    todo: ignore
  exclude:
    - example/matrix_api_lite_example.dart
    - lib/src/generated/**.dart
