name: matrix_api_lite
description: Dead simple data model for the matrix.org client-server API.
version: 1.7.1
homepage: https://famedly.com
repository: https://gitlab.com/famedly/company/frontend/libraries/matrix_api_lite/
issues: https://gitlab.com/famedly/company/frontend/libraries/matrix_api_lite/-/issues

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  enhanced_enum: ^0.2.4
  http: ^0.13.0
  mime: ^1.0.0

dev_dependencies:
  build_runner: ^2.1.8
  enhanced_enum_generator: ^0.2.4
  import_sorter: ^4.6.0
  lints: ^2.0.0
  test: ^1.14.4
 
dependency_overrides:
# uncomment for local development
#  matrix:
#    path: '../famedlysdk'
